#!/bin/bash

HN=`hostname | cut -c1-3`

if [ "$HN" != "dcb" ]; then
   echo This command can only be executed on a DCB
   exit 1
fi

cp -v ../../fw/tcb/TCB_1_0/TCB_1_0.runs/impl_1/TCB_TOP.bit /fw_sw/tcb/prod/type_1/
cp -v ../../fw/tcb/TCB_2_0/TCB_2_0.runs/impl_1/TCB_TOP.bit /fw_sw/tcb/prod/type_2/
cp -v ../../fw/tcb/TCB_3_0/TCB_3_0.runs/impl_1/TCB_TOP.bit /fw_sw/tcb/prod/type_3/
