#!/bin/bash

wdb=$1
if [ -z "$2" ]; then
   wdbaddr=$(echo $wdb | cut -c3-5)
else
   wdbaddr=$2
fi

revision=$(echo info | nc -u $wdb 3000 -w1 | grep "Board Revision" | cut -c25-25)

echo "Found revision ${revision} board"

if [ "$revision" = "G" ]; then
   $MSCBSYS/bin/msc -d $wdb -a $wdbaddr -c "up ../../fw/wdb/wd2_sys_ctrl/wd2_xps_hw/rev_g/implementation/download.bit"
   $MSCBSYS/bin/msc -d $wdb -a $wdbaddr -c "up ../../fw/wdb/wd2_sys_ctrl/wd2_xsdk_sw/rev_g_workspace/wd2_app_sw/app_sys_ctrl/Debug/app_sys_ctrl.srec"
else
   $MSCBSYS/bin/msc -d $wdb -a $wdbaddr -c "up ../../fw/wdb/wd2_sys_ctrl/wd2_xps_hw/rev_f/implementation/download.bit"
   $MSCBSYS/bin/msc -d $wdb -a $wdbaddr -c "up ../../fw/wdb/wd2_sys_ctrl/wd2_xsdk_sw/rev_f_workspace/wd2_app_sw/app_sys_ctrl/Debug/app_sys_ctrl.srec"
fi


