#!/bin/bash -x

dcb=$1

scp ../../fw/wdb/wd2_sys_ctrl/wd2_xps_hw/rev_g/implementation/download.bit root@$dcb:/firmware/wdb/prod/rev_g/
scp ../../fw/wdb/wd2_sys_ctrl/wd2_xsdk_sw/rev_g_workspace/wd2_app_sw/app_sys_ctrl/Debug/app_sys_ctrl.srec root@$dcb:/firmware/wdb/prod/rev_g/

scp ../../fw/wdb/wd2_sys_ctrl/wd2_xps_hw/rev_f/implementation/download.bit root@$dcb:/firmware/wdb/prod/rev_f/
scp ../../fw/wdb/wd2_sys_ctrl/wd2_xsdk_sw/rev_f_workspace/wd2_app_sw/app_sys_ctrl/Debug/app_sys_ctrl.srec root@$dcb:/firmware/wdb/prod/rev_f/

#scp ../../fw/tcb/TCB_1_0/TCB_1_0.runs/impl_1/TCB_TOP.bit root@$dcb:/firmware/tcb/prod/type_1/
#scp ../../fw/tcb/TCB_2_0/TCB_2_0.runs/impl_1/TCB_TOP.bit root@$dcb:/firmware/tcb/prod/type_2/
#scp ../../fw/tcb/TCB_3_0/TCB_3_0.runs/impl_1/TCB_TOP.bit root@$dcb:/firmware/tcb/prod/type_3/


