#!/bin/bash

# Extract number of WDB as address
wdb=$1
wdbaddr=`echo $wdb | cut -c3-5`

$MSCBSYS/bin/msc -d $wdb -a $wdbaddr -c "up ../../firmware/WD2/wd2_sys_ctrl/wd2_xsdk_workspace/wd2_app_sw/app_sys_ctrl/Debug/app_sys_ctrl.srec"

